name: czsl
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cudatoolkit=11.0.221
  - freetype=2.10.4
  - intel-openmp=2020.2=254
  - jpeg=9b
  - lcms2=2.11
  - libffi=3.3
  - libpng=1.6.37
  - libtiff=4.1.0
  - libuv=1.40.0
  - lz4-c=1.9.3
  - mkl=2020.2=256
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46=py_0
  - openssl=1.1.1i
  - pillow=8.1.0
  - pip=20.3.3
  - python=3.8.5
  - pytorch=1.7.1
  - scipy=1.5.2
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - torchaudio=0.7.2=py38
  - torchvision=0.8.2=py38_cu110
  - typing_extensions=3.7.4.3=pyh06a4308_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.11.0
    - cachetools==4.2.1
    - chardet==4.0.0
    - fasttext==0.9.2
    - gensim==3.8.3
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - grpcio==1.35.0
    - idna==2.10
    - markdown==3.3.3
    - oauthlib==3.1.0
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.6.2
    - pyyaml==5.4.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7
    - smart-open==4.1.2
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tqdm==4.56.0
    - urllib3==1.26.3
    - werkzeug==1.0.1

