---
experiment:
  name: DBC/German/German
dataset:
  data_dir: dataset/German
  dataset: German
  splitname: compositional-split-naturalall
model_params:
  emb_dim: 300
training:
  batch_size: 8
  load:
  lr: 0.0001
  max_epochs: 100
  save_every: 10000
  test_batch_size: 8
  test_set: val
  topk: 1
  wd: 5.0e-05
  workers: 4
  drop: 0.0
  res_epoch: 1
