---
experiment:
  name: DBC/utzappos
dataset:
  data_dir: dataset/ut-zappos
  dataset: utzappos
  splitname: compositional-split-natural
model_params:
  emb_dim: 800
training:
  batch_size: 32
  load:
  lr: 0.0001
  max_epochs: 100
  save_every: 10000
  test_batch_size: 32
  test_set: val
  topk: 1
  wd: 5.0e-05
  workers: 4
  drop: 0.3
  res_epoch: 20
